# Generated by Django 6.0.4 on 2026-05-14 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinancialReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('income', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('expense', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('profit', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('budget_after', models.DecimalField(decimal_places=2, max_digits=15)),
                ('operation_type', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'FinancialReports',
            },
        ),
    ]
