# Generated by Django 6.0.4 on 2026-05-14 14:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_financialreport'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreditRepayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('credit', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='repayments', to='dashboard.credit')),
            ],
            options={
                'db_table': 'CreditRepayments',
            },
        ),
    ]
