# Generated by Django 6.0.4 on 2026-05-14 16:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_creditrepayment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeprofile',
            name='role',
            field=models.CharField(choices=[('Admin', 'Админ'), ('Manager', 'Менеджер'), ('Supervisor', 'Супервайзер'), ('Accountant', 'Бухгалтер')], default='Supervisor', max_length=20),
        ),
        migrations.CreateModel(
            name='ProductionRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('applicant_full_name', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('Created', 'Создана'), ('Checking', 'На проверке наличия сырья'), ('Purchasing', 'На процессе закупки сырья'), ('Producing', 'На процессе производства'), ('Selling', 'На процессе продажи'), ('Completed', 'Выполнена'), ('Error', 'Ошибка')], default='Created', max_length=50)),
                ('reject_reason', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('estimated_cost', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('estimated_profit', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('final_budget', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('product', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, to='dashboard.finishedproduct')),
            ],
            options={
                'db_table': 'ProductionRequests',
            },
        ),
        migrations.AddField(
            model_name='financialreport',
            name='related_request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='financial_logs', to='dashboard.productionrequest'),
        ),
    ]
