# Generated by Django 6.0.4 on 2026-05-14 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_alter_employeeprofile_role_productionrequest_and_more'),
    ]

    operations = [
        migrations.RunSQL(
            sql="ALTER TABLE RawMaterialPurchases ADD RelatedRequestID BIGINT NULL;",
            reverse_sql="ALTER TABLE RawMaterialPurchases DROP COLUMN RelatedRequestID;"
        ),
        migrations.RunSQL(
            sql="ALTER TABLE Production ADD RelatedRequestID BIGINT NULL;",
            reverse_sql="ALTER TABLE Production DROP COLUMN RelatedRequestID;"
        ),
        migrations.RunSQL(
            sql="ALTER TABLE Sales ADD RelatedRequestID BIGINT NULL;",
            reverse_sql="ALTER TABLE Sales DROP COLUMN RelatedRequestID;"
        ),
    ]
